### ISSUE TITLE
StockGenerator properties issue

### ISSUE THREAD

**Issue by joseasoler** [Garethp/Rider-RimworldDevelopment#4]
When using the autocomplete in a StockGenerator instance, autocomplete seems to offer the properties of all classes that inherit from StockGenerator, instead of just the ones of the current example

For example, when using auto complete on [this line of TraderGen](https://gitlab.com/joseasoler/tradergen/-/blob/main/1.4/Defs/TraderSpecializationDefs/TG_Specializations.xml#L82) and after typing `<`, since this is a instance of [HemogenicGenepack](https://gitlab.com/joseasoler/tradergen/-/blob/main/Source/StockGen/HemogenicGenepack.cs), the options should only be the ones in the inheritance hierarchy of this type:

* StockGenerator: trader, countRange, customCountRanges, totalPriceRange, maxTechLevelGenerate, maxTechLevelBuy, price
* StockGen: forceFactionTechLimits
* ConditionMatcher: thingDefCountRange, minTechLevelGenerate
* CustomGenepack: architeGenes, nonArchiteGenes

**Comment by Garethp** [comment]
So it turns out I'm not able to disable the *extra* autocompletions, those come from Rider by default as XML and I can only add to the list of suggestions. Rather than autocompleting items that extend from `StockGenerator`, those extra suggestions are just Rider noticing that you've used those tags somewhere else in the XML file and therefore they might apply here (even though they don't).

What I *did* notice was that in that example `architeGenes` and `nonArchiteGenes` for example *weren't* coming through my plugin (The easy way to tell is if they have a Class Name on the right, they're from my plugin otherwise they're part of the default suggestions). For some reason it wasn't picking up some of the classes to pull properties from. That's been fixed and will be released with Alpha-3
